"""
Render derived analysis results into MediaWiki pages.

Pure functions: derived/ outputs in, wikitext + an image-upload manifest
out (written under derived/wiki/). Nothing here touches the network, so
page rendering is fully testable offline; publishing the rendered bundle
is src/wiki/publish.py's job.

Page structure (matching the project goals):
- MAIN page: written for non-technical Miniscope users. Quality-score vs
  length per data rate (one curve per cable), supply-voltage guidance per
  Miniscope model, links to per-cable detail pages.
- PROFILE pages: full detail for one cable -- specs, resistivity,
  eye diagrams, link margin, attenuation.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import yaml

from src.wiki.config import WikiConfig, load_wiki_config

logger = logging.getLogger(__name__)

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by miniscope-wired-interconnect-characterization. -->\n"
    "<!-- Do not edit by hand: changes are overwritten on the next data merge. -->\n"
)


@dataclass
class ImageUpload:
    """One plot to upload: local file -> wiki filename."""

    local_path: Path
    wiki_name: str


def _wiki_table(df: pd.DataFrame, columns: dict[str, str]) -> str:
    """Render selected DataFrame columns as a MediaWiki table."""
    lines = ['{| class="wikitable"', "|-"]
    lines.extend(f"! {label}" for label in columns.values())
    for _, row in df.iterrows():
        lines.append("|-")
        for col in columns:
            value = row.get(col)
            if isinstance(value, float):
                value = f"{value:g}"
            lines.append(f"| {value if value is not None else ''}")
    lines.append("|}")
    return "\n".join(lines)


def _image_ref(wiki_name: str, caption: str, width: int = 640) -> str:
    return f"[[File:{wiki_name}|{width}px|thumb|none|{caption}]]"


# Shown under the SerDes table whenever some length/rate did not link. It
# reframes a no-link as a measured result -- and, for short cables, as a
# minimum-cable-length effect rather than a damaged cable -- so readers do not
# misread a not-recommended short length as a bad cable.
_NO_LINK_NOTE = (
    "'''Why a length may show \"Links? = False\":''' the link did not "
    "establish reliably at that rate on the bench, so it is scored 0 (not "
    "recommended) for that rate -- this is a measured outcome, not a missing "
    "measurement. A no-link at a ''short'' length does not mean the cable is "
    "damaged: a GMSL2 receiver adapts its equalizer to the cable's loss, and a "
    "very short, near-lossless cable can fall below the link's minimum "
    'insertion-loss requirement (the channel is "too clean" for the receiver to '
    "lock). In that regime a cable can be too short to link even though its "
    "attenuation looks excellent -- the VNA attenuation for that length is still "
    "valid and is reported below."
)


def _has_no_link(df: pd.DataFrame) -> bool:
    """True if any row's 'linked' is falsey (CSV may give bools or strings)."""
    if "linked" not in df.columns:
        return False
    linked = df["linked"].map(lambda v: str(v).strip().lower() in ("true", "1"))
    return not bool(linked.all())


class WikiRenderer:
    """Builds the page set + image manifest from derived/ outputs."""

    def __init__(self, repo_root: Path, config: WikiConfig) -> None:
        self.repo_root = repo_root
        self.config = config
        self.images: list[ImageUpload] = []

    # ---------- helpers ----------

    def _register_image(self, local_path: Path) -> str | None:
        """Queue an image for upload; returns its wiki filename."""
        if not local_path.exists():
            return None
        wiki_name = self.config.image_prefix + "_".join(
            local_path.relative_to(self.repo_root / "derived").parts
        )
        self.images.append(ImageUpload(local_path=local_path, wiki_name=wiki_name))
        return wiki_name

    def _cross_csv(self, name: str) -> pd.DataFrame | None:
        path = self.repo_root / "derived" / "cross" / name
        if not path.exists():
            return None
        return pd.read_csv(path)

    # ---------- main page ----------

    def render_main_page(self, profile_ids: list[str]) -> str:
        cross_dir = self.repo_root / "derived" / "cross"
        parts: list[str] = [GENERATED_BANNER]

        parts.append(
            "This page summarizes measured performance of coaxial tether cables "
            "for Miniscopes: which cables work at which lengths, and what supply "
            "voltage your cable needs. Detailed per-cable results are linked at "
            "the bottom.\n"
        )

        # Quality score vs length, per rate
        parts.append("== Which cable lengths work? ==\n")
        parts.append(
            "Each curve is one cable type. The score combines eye opening, link "
            "margin, and attenuation into a single 0-1 number; the shaded bands "
            "show the recommended (green), marginal (yellow), and "
            "not-recommended (red) regions.\n"
        )
        for plot in sorted(cross_dir.glob("quality_vs_length_*g.png")):
            rate = plot.stem.replace("quality_vs_length_", "").replace("g", "")
            wiki_name = self._register_image(plot)
            if wiki_name:
                parts.append(_image_ref(wiki_name, f"Cable quality vs length at {rate} Gbps"))

        quality_df = self._cross_csv("quality_scores.csv")
        if quality_df is not None:
            parts.append("\n=== Summary table ===\n")
            parts.append(
                _wiki_table(
                    quality_df,
                    {
                        "profile_id": "Cable",
                        "cable_length_mm": "Length (mm)",
                        "rate_gbps": "Rate (Gbps)",
                        "quality_score": "Score",
                        "zone": "Recommendation",
                    },
                )
            )

        # Per-miniscope quality at the miniscope's own link rate
        miniscope_quality_df = self._cross_csv("miniscope_quality.csv")
        if miniscope_quality_df is not None:
            parts.append("\n== Which cable works with my Miniscope? ==\n")
            parts.append(
                "Each Miniscope runs its link at one rate, so these curves show "
                "cable quality at that rate. Curves marked ''projected'' are "
                "derived from the cable's measured attenuation rather than a "
                "direct eye measurement.\n"
            )
            for plot in sorted(cross_dir.glob("miniscope_quality_*.png")):
                scope = plot.stem.replace("miniscope_quality_", "")
                wiki_name = self._register_image(plot)
                if wiki_name:
                    parts.append(_image_ref(wiki_name, f"Cable quality vs length ({scope})"))
            parts.append(
                _wiki_table(
                    miniscope_quality_df,
                    {
                        "miniscope_model": "Miniscope",
                        "profile_id": "Cable",
                        "cable_length_mm": "Length (mm)",
                        "rate_gbps": "Rate (Gbps)",
                        "quality_score": "Score",
                        "zone": "Recommendation",
                        "source": "Source",
                    },
                )
            )

        # Supply voltage guidance
        parts.append("\n== What supply voltage do I need? ==\n")
        parts.append(
            "Thin coax drops voltage, so each cable and length has an allowable "
            "supply window: the minimum keeps the Miniscope above its regulator "
            "dropout at full load; the maximum stays under the regulator's input "
            "limit. The dotted line marks the USB 5 V rail for reference -- DAQs "
            "can also be powered from an adjustable supply anywhere in the window.\n"
        )
        parts.append(
            "When the minimum exceeds the maximum the window is empty "
            "(''Feasible? = No''): no single supply can hold the Miniscope above "
            "dropout at full load and under its input limit at idle at the same "
            "time, so the cable is too long/resistive for that model's current "
            "range -- it is not a swapped reading.\n"
        )
        for plot in sorted(cross_dir.glob("supply_voltage_*.png")):
            scope = plot.stem.replace("supply_voltage_", "")
            wiki_name = self._register_image(plot)
            if wiki_name:
                parts.append(_image_ref(wiki_name, f"Allowable supply voltage ({scope})"))

        supply_df = self._cross_csv("supply_voltage.csv")
        if supply_df is not None:
            parts.append(
                _wiki_table(
                    supply_df,
                    {
                        "miniscope_model": "Miniscope",
                        "profile_id": "Cable",
                        "cable_length_mm": "Length (mm)",
                        "v_supply_min": "Min supply (V)",
                        "v_supply_max": "Max supply (V)",
                        "feasible": "Feasible?",
                        "reference_supply_ok": "OK at 5 V (USB)?",
                    },
                )
            )

        max_length_df = self._cross_csv("max_length_summary.csv")
        if max_length_df is not None:
            parts.append("\n=== Longest usable cable on USB (5 V) power ===\n")
            parts.append(
                _wiki_table(
                    max_length_df,
                    {
                        "miniscope_model": "Miniscope",
                        "profile_id": "Cable",
                        "reference_supply_v": "Supply (V)",
                        "voltage_limited_max_length_mm": "Max length (mm)",
                    },
                )
            )

        # Commutator standalone impact
        impact_df = self._cross_csv("commutator_impact.csv")
        if impact_df is not None:
            parts.append("\n== What does a commutator cost? ==\n")
            parts.append(
                "A commutator sits in series in the tether, so it adds its own "
                "resistance (raising the required supply and eating cable "
                "budget) and its own insertion loss at the link frequency. "
                "These are standalone numbers -- add them on top of your "
                "cable's.\n"
            )
            parts.append(
                _wiki_table(
                    impact_df,
                    {
                        "commutator_id": "Commutator",
                        "miniscope_model": "Miniscope",
                        "added_resistance_ohm": "Added resistance (ohm)",
                        "supply_floor_increase_v": "Min supply increase (V)",
                        "added_attenuation_db": "Added attenuation (dB)",
                    },
                )
            )
            length_impact_df = self._cross_csv("commutator_length_impact.csv")
            if length_impact_df is not None:
                parts.append("\n=== Cable length budget it consumes ===\n")
                parts.append(
                    _wiki_table(
                        length_impact_df,
                        {
                            "commutator_id": "Commutator",
                            "profile_id": "Cable",
                            "max_length_reduction_mm": "Max length reduction (mm)",
                        },
                    )
                )

        # Links to detail pages
        parts.append("\n== Per-DUT details ==\n")
        for profile_id in sorted(profile_ids):
            parts.append(f"* [[{self.config.profile_page(profile_id)}|{profile_id}]]")

        return "\n".join(parts) + "\n"

    # ---------- profile pages ----------

    def render_profile_page(self, profile_id: str) -> str:
        parts: list[str] = [GENERATED_BANNER]

        # Specs from the profile YAML
        profile_path = self.repo_root / "profiles" / f"{profile_id}.yaml"
        if profile_path.exists():
            with open(profile_path) as f:
                profile = yaml.safe_load(f)
            parts.append("== Cable specifications ==\n")
            spec_rows = [
                {"field": k.replace("_", " "), "value": v}
                for k, v in profile.items()
                if k not in ("schema_version",) and v not in (None, "", [])
            ]
            parts.append(
                _wiki_table(pd.DataFrame(spec_rows), {"field": "Property", "value": "Value"})
            )

        # Resistivity (from the cross fit)
        resistivity_df = self._cross_csv("resistivity_summary.csv")
        if resistivity_df is not None:
            row = resistivity_df[resistivity_df["profile_id"] == profile_id]
            if not row.empty:
                r = row.iloc[0]
                parts.append("\n== Round-trip resistivity ==\n")
                parts.append(
                    f"Measured round-trip resistivity: "
                    f"'''{r['roundtrip_resistivity_ohm_per_m']:g} ohm/m''' "
                    f"({r['method']}, n={int(r['n_lengths'])} lengths"
                    + (
                        f", connector intercept {r['intercept_ohm']:g} ohm"
                        if pd.notna(r.get("intercept_ohm"))
                        else ""
                    )
                    + (f", R2={r['r_squared']:g}" if pd.notna(r.get("r_squared")) else "")
                    + ")."
                )

        profile_derived = self.repo_root / "derived" / "profiles" / profile_id

        # SerDes results: consolidated table + newest eye diagrams per length
        serdes_csv = profile_derived / "serdes_by_length.csv"
        if serdes_csv.exists():
            parts.append("\n== SerDes signal integrity ==\n")
            df = pd.read_csv(serdes_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "cable_length_mm": "Length (mm)",
                        "lane_id": "Lane",
                        "channel": "Channel",
                        "rate_gbps": "Rate (Gbps)",
                        "linked": "Links?",
                        "mean_eye_area_ratio": "Eye area",
                        "mean_eye_height_mv": "Eye height (mV)",
                        "mean_eye_width_ps": "Eye width (ps)",
                        "mean_link_margin_mv": "Margin floor (mV)",
                        "n_sessions": "Sessions",
                    },
                )
            )

            if _has_no_link(df):
                parts.append("\n" + _NO_LINK_NOTE)

            parts.append("\n=== Eye diagrams ===\n")
            for png in sorted(
                (self.repo_root / "derived" / "sessions" / profile_id).rglob("eye_*.png")
            ):
                wiki_name = self._register_image(png)
                if wiki_name:
                    session_ref = "/".join(
                        png.relative_to(self.repo_root / "derived" / "sessions").parts[:-1]
                    )
                    parts.append(_image_ref(wiki_name, f"{png.stem} ({session_ref})", width=420))

            for plot_name, caption in [
                ("serdes_eye_vs_length.png", "Eye opening vs cable length"),
                ("serdes_margin_vs_length.png", "Link margin vs cable length"),
            ]:
                wiki_name = self._register_image(
                    self.repo_root / "derived" / "aggregated" / "serdes" / plot_name
                )
                if wiki_name:
                    parts.append(_image_ref(wiki_name, caption))

        # VNA results
        vna_csv = profile_derived / "vna_by_length.csv"
        if vna_csv.exists():
            parts.append("\n== RF attenuation (VNA) ==\n")
            df = pd.read_csv(vna_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "cable_length_mm": "Length (mm)",
                        "mean_max_insertion_loss_db": "Mean worst insertion loss (dB)",
                        "worst_max_insertion_loss_db": "Worst insertion loss (dB)",
                        "n_sessions": "Sessions",
                    },
                )
            )
            wiki_name = self._register_image(
                self.repo_root / "derived" / "aggregated" / "vna" / "vna_comparison.png"
            )
            if wiki_name:
                parts.append(_image_ref(wiki_name, "Attenuation vs frequency"))

            imp_name = self._register_image(
                self.repo_root / "derived" / "aggregated" / "vna" / "vna_impedance.png"
            )
            if imp_name:
                parts.append(_image_ref(imp_name, "Characteristic impedance vs frequency"))

        # Resistance results
        resistance_csv = profile_derived / "resistance_by_length.csv"
        if resistance_csv.exists():
            parts.append("\n== Resistance measurements ==\n")
            df = pd.read_csv(resistance_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "cable_length_mm": "Length (mm)",
                        "mean_roundtrip_resistance_ohm_per_m": "Round-trip ohm/m (mean)",
                        "std_roundtrip_resistance_ohm_per_m": "Round-trip ohm/m (std)",
                        "n_sessions": "Sessions",
                        "total_measurements": "Measurements",
                    },
                )
            )

        parts.append(f"\n''Back to [[{self.config.main_page}]]''")
        return "\n".join(parts) + "\n"

    # ---------- commutator pages ----------

    def render_commutator_page(self, profile_id: str) -> str:
        parts: list[str] = [GENERATED_BANNER]

        # Specs from the profile YAML
        profile_path = self.repo_root / "profiles" / f"{profile_id}.yaml"
        if profile_path.exists():
            with open(profile_path) as f:
                profile = yaml.safe_load(f)
            parts.append("== Commutator specifications ==\n")
            spec_rows = [
                {"field": k.replace("_", " "), "value": v}
                for k, v in profile.items()
                if k not in ("schema_version",) and v not in (None, "", [])
            ]
            parts.append(
                _wiki_table(pd.DataFrame(spec_rows), {"field": "Property", "value": "Value"})
            )

        profile_derived = self.repo_root / "derived" / "profiles" / profile_id

        # Standalone impact (the headline result)
        impact_df = self._cross_csv("commutator_impact.csv")
        if impact_df is not None:
            scoped = impact_df[impact_df["commutator_id"] == profile_id]
            if not scoped.empty:
                parts.append("\n== Impact on your link ==\n")
                parts.append(
                    "Adding this commutator to a tether costs, on top of the " "cable itself:\n"
                )
                parts.append(
                    _wiki_table(
                        scoped,
                        {
                            "miniscope_model": "Miniscope",
                            "added_resistance_ohm": "Added resistance (ohm)",
                            "supply_floor_increase_v": "Min supply increase (V)",
                            "added_attenuation_db": "Added attenuation (dB)",
                        },
                    )
                )
        length_impact_df = self._cross_csv("commutator_length_impact.csv")
        if length_impact_df is not None:
            scoped = length_impact_df[length_impact_df["commutator_id"] == profile_id]
            if not scoped.empty:
                parts.append("\n=== Cable length budget consumed ===\n")
                parts.append(
                    _wiki_table(
                        scoped,
                        {
                            "profile_id": "Cable",
                            "max_length_reduction_mm": "Max length reduction (mm)",
                        },
                    )
                )

        # Measured series resistance
        resistance_csv = profile_derived / "resistance_by_length.csv"
        if resistance_csv.exists():
            parts.append("\n== Series resistance ==\n")
            df = pd.read_csv(resistance_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "condition": "Condition",
                        "mean_roundtrip_resistance_ohm": "Round-trip ohm (mean)",
                        "std_roundtrip_resistance_ohm": "Round-trip ohm (std)",
                        "n_sessions": "Sessions",
                        "total_measurements": "Measurements",
                    },
                )
            )

        # SerDes through the commutator
        serdes_csv = profile_derived / "serdes_by_length.csv"
        if serdes_csv.exists():
            parts.append("\n== SerDes signal integrity (through the commutator) ==\n")
            df = pd.read_csv(serdes_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "condition": "Condition",
                        "lane_id": "Lane",
                        "channel": "Channel",
                        "rate_gbps": "Rate (Gbps)",
                        "linked": "Links?",
                        "mean_eye_area_ratio": "Eye area",
                        "mean_eye_height_mv": "Eye height (mV)",
                        "mean_eye_width_ps": "Eye width (ps)",
                        "mean_link_margin_mv": "Margin floor (mV)",
                        "n_sessions": "Sessions",
                    },
                )
            )
            for png in sorted(
                (self.repo_root / "derived" / "sessions" / profile_id).rglob("eye_*.png")
            ):
                wiki_name = self._register_image(png)
                if wiki_name:
                    session_ref = "/".join(
                        png.relative_to(self.repo_root / "derived" / "sessions").parts[:-1]
                    )
                    parts.append(_image_ref(wiki_name, f"{png.stem} ({session_ref})", width=420))

        # VNA insertion loss
        vna_csv = profile_derived / "vna_by_length.csv"
        if vna_csv.exists():
            parts.append("\n== RF insertion loss (VNA) ==\n")
            df = pd.read_csv(vna_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "condition": "Condition",
                        "mean_max_insertion_loss_db": "Mean worst insertion loss (dB)",
                        "worst_max_insertion_loss_db": "Worst insertion loss (dB)",
                        "n_sessions": "Sessions",
                    },
                )
            )

        parts.append(f"\n''Back to [[{self.config.main_page}]]''")
        return "\n".join(parts) + "\n"


def render_wiki(repo_root: Path) -> dict[str, Path]:
    """
    Render the full wiki bundle into derived/wiki/:
    - pages/<safe_title>.wiki      wikitext per page
    - upload_manifest.json         page titles + image uploads
    """
    config = load_wiki_config(repo_root / "config" / "wiki.yaml")
    renderer = WikiRenderer(repo_root, config)

    profiles_dir = repo_root / "profiles"
    profile_ids = (
        sorted(p.stem for p in profiles_dir.glob("*.yaml")) if profiles_dir.exists() else []
    )

    # Cable vs commutator pages differ; dispatch on the profile_type field
    def _kind(profile_id: str) -> str:
        try:
            with open(profiles_dir / f"{profile_id}.yaml") as f:
                return (yaml.safe_load(f) or {}).get("profile_type", "cable")
        except Exception:
            return "cable"

    pages: dict[str, str] = {config.main_page: renderer.render_main_page(profile_ids)}
    for profile_id in profile_ids:
        if _kind(profile_id) == "commutator":
            pages[config.profile_page(profile_id)] = renderer.render_commutator_page(profile_id)
        else:
            pages[config.profile_page(profile_id)] = renderer.render_profile_page(profile_id)

    output_dir = repo_root / "derived" / "wiki"
    pages_dir = output_dir / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    outputs: dict[str, Path] = {}
    manifest: dict = {"pages": [], "images": []}

    for title, text in pages.items():
        safe_name = title.replace("/", "__").replace(" ", "_") + ".wiki"
        page_path = pages_dir / safe_name
        page_path.write_text(text, encoding="utf-8")
        manifest["pages"].append({"title": title, "file": f"pages/{safe_name}"})
        outputs[f"page_{title}"] = page_path

    for image in renderer.images:
        manifest["images"].append(
            {
                "local_path": str(image.local_path.relative_to(repo_root)),
                "wiki_name": image.wiki_name,
            }
        )

    manifest_path = output_dir / "upload_manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    outputs["upload_manifest"] = manifest_path

    return outputs
