"""
Render derived analysis results into MediaWiki pages.

Pure functions: derived/ outputs in, wikitext + an image-upload manifest
out (written under derived/wiki/). Nothing here touches the network, so
page rendering is fully testable offline; publishing the rendered bundle
is src/wiki/publish.py's job.

Page structure (matching the project goals):
- MAIN page: written for non-technical Miniscope users. Quality-score vs
  length per data rate (one curve per cable), supply-voltage guidance per
  Miniscope model, links to per-cable detail pages.
- PROFILE pages: full detail for one cable -- specs, resistivity,
  eye diagrams, link margin, attenuation.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import yaml

from src.wiki.config import WikiConfig, load_wiki_config

logger = logging.getLogger(__name__)

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by miniscope-wired-interconnect-characterization. -->\n"
    "<!-- Do not edit by hand: changes are overwritten on the next data merge. -->\n"
)


@dataclass
class ImageUpload:
    """One plot to upload: local file -> wiki filename."""

    local_path: Path
    wiki_name: str


def _wiki_table(df: pd.DataFrame, columns: dict[str, str]) -> str:
    """Render selected DataFrame columns as a MediaWiki table."""
    lines = ['{| class="wikitable"', "|-"]
    lines.extend(f"! {label}" for label in columns.values())
    for _, row in df.iterrows():
        lines.append("|-")
        for col in columns:
            value = row.get(col)
            if isinstance(value, float):
                value = f"{value:g}"
            lines.append(f"| {value if value is not None else ''}")
    lines.append("|}")
    return "\n".join(lines)


def _image_ref(wiki_name: str, caption: str, width: int = 640) -> str:
    return f"[[File:{wiki_name}|{width}px|thumb|none|{caption}]]"


class WikiRenderer:
    """Builds the page set + image manifest from derived/ outputs."""

    def __init__(self, repo_root: Path, config: WikiConfig) -> None:
        self.repo_root = repo_root
        self.config = config
        self.images: list[ImageUpload] = []

    # ---------- helpers ----------

    def _register_image(self, local_path: Path) -> str | None:
        """Queue an image for upload; returns its wiki filename."""
        if not local_path.exists():
            return None
        wiki_name = self.config.image_prefix + "_".join(
            local_path.relative_to(self.repo_root / "derived").parts
        )
        self.images.append(ImageUpload(local_path=local_path, wiki_name=wiki_name))
        return wiki_name

    def _cross_csv(self, name: str) -> pd.DataFrame | None:
        path = self.repo_root / "derived" / "cross" / name
        if not path.exists():
            return None
        return pd.read_csv(path)

    # ---------- main page ----------

    def render_main_page(self, profile_ids: list[str]) -> str:
        cross_dir = self.repo_root / "derived" / "cross"
        parts: list[str] = [GENERATED_BANNER]

        parts.append(
            "This page summarizes measured performance of coaxial tether cables "
            "for Miniscopes: which cables work at which lengths, and what supply "
            "voltage your cable needs. Detailed per-cable results are linked at "
            "the bottom.\n"
        )

        # Quality score vs length, per rate
        parts.append("== Which cable lengths work? ==\n")
        parts.append(
            "Each curve is one cable type. The score combines eye opening, link "
            "margin, and attenuation into a single 0-1 number; the shaded bands "
            "show the recommended (green), marginal (yellow), and "
            "not-recommended (red) regions.\n"
        )
        for plot in sorted(cross_dir.glob("quality_vs_length_*g.png")):
            rate = plot.stem.replace("quality_vs_length_", "").replace("g", "")
            wiki_name = self._register_image(plot)
            if wiki_name:
                parts.append(_image_ref(wiki_name, f"Cable quality vs length at {rate} Gbps"))

        quality_df = self._cross_csv("quality_scores.csv")
        if quality_df is not None:
            parts.append("\n=== Summary table ===\n")
            parts.append(
                _wiki_table(
                    quality_df,
                    {
                        "profile_id": "Cable",
                        "cable_length_mm": "Length (mm)",
                        "rate_gbps": "Rate (Gbps)",
                        "quality_score": "Score",
                        "zone": "Recommendation",
                    },
                )
            )

        # Supply voltage guidance
        parts.append("\n== What supply voltage do I need? ==\n")
        parts.append(
            "Thin coax drops voltage, so each cable and length has an allowable "
            "supply window: the minimum keeps the Miniscope above its regulator "
            "dropout at full load; the maximum stays under the regulator's input "
            "limit. The dotted line is the default supply (typically 5 V USB).\n"
        )
        for plot in sorted(cross_dir.glob("supply_voltage_*.png")):
            scope = plot.stem.replace("supply_voltage_", "")
            wiki_name = self._register_image(plot)
            if wiki_name:
                parts.append(_image_ref(wiki_name, f"Allowable supply voltage ({scope})"))

        supply_df = self._cross_csv("supply_voltage.csv")
        if supply_df is not None:
            parts.append(
                _wiki_table(
                    supply_df,
                    {
                        "miniscope_model": "Miniscope",
                        "profile_id": "Cable",
                        "cable_length_mm": "Length (mm)",
                        "v_supply_min": "Min supply (V)",
                        "v_supply_max": "Max supply (V)",
                        "default_supply_ok": "OK at default supply?",
                    },
                )
            )

        max_length_df = self._cross_csv("max_length_summary.csv")
        if max_length_df is not None:
            parts.append("\n=== Longest usable cable at the default supply ===\n")
            parts.append(
                _wiki_table(
                    max_length_df,
                    {
                        "miniscope_model": "Miniscope",
                        "profile_id": "Cable",
                        "default_supply_v": "Default supply (V)",
                        "voltage_limited_max_length_mm": "Max length (mm)",
                    },
                )
            )

        # Links to detail pages
        parts.append("\n== Per-cable details ==\n")
        for profile_id in sorted(profile_ids):
            parts.append(f"* [[{self.config.profile_page(profile_id)}|{profile_id}]]")

        return "\n".join(parts) + "\n"

    # ---------- profile pages ----------

    def render_profile_page(self, profile_id: str) -> str:
        parts: list[str] = [GENERATED_BANNER]

        # Specs from the profile YAML
        profile_path = self.repo_root / "profiles" / f"{profile_id}.yaml"
        if profile_path.exists():
            with open(profile_path) as f:
                profile = yaml.safe_load(f)
            parts.append("== Cable specifications ==\n")
            spec_rows = [
                {"field": k.replace("_", " "), "value": v}
                for k, v in profile.items()
                if k not in ("schema_version",) and v not in (None, "", [])
            ]
            parts.append(
                _wiki_table(pd.DataFrame(spec_rows), {"field": "Property", "value": "Value"})
            )

        # Resistivity (from the cross fit)
        resistivity_df = self._cross_csv("resistivity_summary.csv")
        if resistivity_df is not None:
            row = resistivity_df[resistivity_df["profile_id"] == profile_id]
            if not row.empty:
                r = row.iloc[0]
                parts.append("\n== Round-trip resistivity ==\n")
                parts.append(
                    f"Measured round-trip resistivity: "
                    f"'''{r['roundtrip_resistivity_ohm_per_m']:g} ohm/m''' "
                    f"({r['method']}, n={int(r['n_lengths'])} lengths"
                    + (
                        f", connector intercept {r['intercept_ohm']:g} ohm"
                        if pd.notna(r.get("intercept_ohm"))
                        else ""
                    )
                    + (f", R2={r['r_squared']:g}" if pd.notna(r.get("r_squared")) else "")
                    + ")."
                )

        profile_derived = self.repo_root / "derived" / "profiles" / profile_id

        # SerDes results: consolidated table + newest eye diagrams per length
        serdes_csv = profile_derived / "serdes_by_length.csv"
        if serdes_csv.exists():
            parts.append("\n== SerDes signal integrity ==\n")
            df = pd.read_csv(serdes_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "cable_length_mm": "Length (mm)",
                        "channel": "Channel",
                        "rate_gbps": "Rate (Gbps)",
                        "mean_eye_area_ratio": "Eye area",
                        "mean_eye_height_mv": "Eye height (mV)",
                        "mean_eye_width_ps": "Eye width (ps)",
                        "mean_link_margin_mv": "Margin floor (mV)",
                        "n_sessions": "Sessions",
                    },
                )
            )

            parts.append("\n=== Eye diagrams ===\n")
            for png in sorted(
                (self.repo_root / "derived" / "sessions" / profile_id).rglob("eye_*.png")
            ):
                wiki_name = self._register_image(png)
                if wiki_name:
                    session_ref = "/".join(
                        png.relative_to(self.repo_root / "derived" / "sessions").parts[:-1]
                    )
                    parts.append(_image_ref(wiki_name, f"{png.stem} ({session_ref})", width=420))

            for plot_name, caption in [
                ("serdes_eye_vs_length.png", "Eye opening vs cable length"),
                ("serdes_margin_vs_length.png", "Link margin vs cable length"),
            ]:
                wiki_name = self._register_image(
                    self.repo_root / "derived" / "aggregated" / "serdes" / plot_name
                )
                if wiki_name:
                    parts.append(_image_ref(wiki_name, caption))

        # VNA results
        vna_csv = profile_derived / "vna_by_length.csv"
        if vna_csv.exists():
            parts.append("\n== RF attenuation (VNA) ==\n")
            df = pd.read_csv(vna_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "cable_length_mm": "Length (mm)",
                        "mean_max_insertion_loss_db": "Mean worst insertion loss (dB)",
                        "worst_max_insertion_loss_db": "Worst insertion loss (dB)",
                        "n_sessions": "Sessions",
                    },
                )
            )
            wiki_name = self._register_image(
                self.repo_root / "derived" / "aggregated" / "vna" / "vna_comparison.png"
            )
            if wiki_name:
                parts.append(_image_ref(wiki_name, "Attenuation vs frequency"))

            imp_name = self._register_image(
                self.repo_root / "derived" / "aggregated" / "vna" / "vna_impedance.png"
            )
            if imp_name:
                parts.append(_image_ref(imp_name, "Characteristic impedance vs frequency"))

        # Resistance results
        resistance_csv = profile_derived / "resistance_by_length.csv"
        if resistance_csv.exists():
            parts.append("\n== Resistance measurements ==\n")
            df = pd.read_csv(resistance_csv)
            parts.append(
                _wiki_table(
                    df,
                    {
                        "cable_length_mm": "Length (mm)",
                        "mean_roundtrip_resistance_ohm_per_m": "Round-trip ohm/m (mean)",
                        "std_roundtrip_resistance_ohm_per_m": "Round-trip ohm/m (std)",
                        "n_sessions": "Sessions",
                        "total_measurements": "Measurements",
                    },
                )
            )

        parts.append(f"\n''Back to [[{self.config.main_page}]]''")
        return "\n".join(parts) + "\n"


def render_wiki(repo_root: Path) -> dict[str, Path]:
    """
    Render the full wiki bundle into derived/wiki/:
    - pages/<safe_title>.wiki      wikitext per page
    - upload_manifest.json         page titles + image uploads
    """
    config = load_wiki_config(repo_root / "config" / "wiki.yaml")
    renderer = WikiRenderer(repo_root, config)

    profiles_dir = repo_root / "profiles"
    profile_ids = (
        sorted(p.stem for p in profiles_dir.glob("*.yaml")) if profiles_dir.exists() else []
    )

    pages: dict[str, str] = {config.main_page: renderer.render_main_page(profile_ids)}
    for profile_id in profile_ids:
        pages[config.profile_page(profile_id)] = renderer.render_profile_page(profile_id)

    output_dir = repo_root / "derived" / "wiki"
    pages_dir = output_dir / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    outputs: dict[str, Path] = {}
    manifest: dict = {"pages": [], "images": []}

    for title, text in pages.items():
        safe_name = title.replace("/", "__").replace(" ", "_") + ".wiki"
        page_path = pages_dir / safe_name
        page_path.write_text(text, encoding="utf-8")
        manifest["pages"].append({"title": title, "file": f"pages/{safe_name}"})
        outputs[f"page_{title}"] = page_path

    for image in renderer.images:
        manifest["images"].append(
            {
                "local_path": str(image.local_path.relative_to(repo_root)),
                "wiki_name": image.wiki_name,
            }
        )

    manifest_path = output_dir / "upload_manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    outputs["upload_manifest"] = manifest_path

    return outputs
